# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 七分配的Sam
subtitle: '纸上得来终觉浅,绝知此事需躬行|博客搭建、开关电源、跑步日常'
description: '这是一个融合技术与生活的个人博客，聚焦开关电源设计、电子电路调试、元器件选型等硬核内容，从原理剖析到实战案例，分享电路设计中的避坑经验与创新思路，适合电子爱好者和从业者交流学习。同时，这里也记录着跑步日常以及生活随笔里的点滴感悟。技术的严谨与生活的温度在此交织，既为同好提供专业参考，也为自己留存一段真实鲜活的成长轨迹。'
keywords: ['开关电源','电子设计','跑步日常','生活随笔','博客搭建','个人博客']
author: Sam
avatar: https://u.sam7.top/3MiiTn
language:
  - zh-CN
  - en
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://sam7.top
permalink: :category/:title/ #:year/:month/:day/:title/
abbrlink:
  alg: crc32  #算法： crc16(default) and crc32
  rep: dec    #进制： dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight: 
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: false
prismjs:
  enable: false
  preprocess: false
  line_number: false
  tab_replace: ''


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar
#remote_theme: sam7xx/stellar
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:sam7xx/sam7xx.github.io.git
  branch: main
  message: "Hexo deploy: {{ now('YYYY-MM-DD HH:mm:ss') }}"  

aplayer:
  # 示例配置
  cdn: https://cdn.jsdmirror.com/npm/aplayer@latest/dist/APlayer.min.js
  style_cdn: https://cdn.jsdmirror.com/npm/aplayer@latest/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdmirror.com/npm/meting@1/dist/Meting.min.js

feed:
  type: atom # RSS的类型(atom/rss2)
  path: atom.xml # 文件路径,默认是atom.xml/rss2.xml
  limit: 20 # 展示文章的数量,使用0或则false代表展示全部hub
#  hub:
#    content:  # 在RSS文件中是否包含内容 ,有3个值 true/false默认不填为false
#    content_limit: # 指定内容的长度作为摘要,仅仅在上面content设置为false和没有自定义的描述出现
#    content_limit_delim: ' ' #上面截取描述的分隔符,截取内容是以指定的这个分隔符作为截取结束的标志.在达到规定的内容长度之前最后出现的这个分隔符之前的内容，防止从中间截断

# 标准 sitemap 配置
sitemap:
  path: sitemap.xml
  url: https://sam7.top
  # 注释掉 template 配置，使用插件默认模板
  template: ./sitemap_template.xml
  changefreq: monthly
  priority: 0.6
# 百度 sitemap 配置
baidusitemap:
  path: baidusitemap.xml  # 百度专用站点地图

autonofollow:
  enable: true
  exclude:
    - https://sam7.top  # 信任的站点，不加nofollow

# seo_autopush:
#   # 是否启用插件
#   enable: true
#   # 推送的搜索引擎（支持百度、谷歌等，按需添加）
#   providers:
#     # 百度搜索资源平台推送（需先在百度验证站点）
#     baidu:
#       # 百度站点的 token（从百度搜索资源平台获取）
#       token: "你的百度站点token"
#       # 推送类型：自动推送（auto）或手动推送（manual），默认 auto
#       type: "auto"
#     # 谷歌搜索控制台推送（可选）
#     google:
#       # 谷歌站点的 API 密钥（从谷歌云平台获取）
#       apiKey: "你的谷歌API密钥"
#       # 谷歌站点的站点ID（从谷歌搜索控制台获取）
#       siteId: "你的谷歌站点ID"
#   # 是否只在生产环境（hexo generate）时推送（推荐 true，避免开发时重复推送）
#   onlyProduction: true

all_minifier: true

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

# hexo-ai-summary-liushen
# docs on : https://github.com/willow-god/hexo-ai-summary
aisummary:
  # 基本控制
  enable: false               # 是否启用插件，如果关闭，也可以在文章顶部的is_summary字段单独设置是否启用，反之也可以配置是否单独禁用
  cover_all: false           # 是否覆盖已有摘要，默认只生成缺失的，注意开启后，可能会导致过量的api使用！
  summary_field: summary     # 摘要写入字段名（建议保留为 summary），重要配置，谨慎修改！！！！！！！
  logger: 1                  # 日志等级（0=仅错误，1=生成+错误，2=全部）

  # AI 接口配置
  api: https://api.openai.com/v1/chat/completions     # OpenAI 兼容模型接口
  token: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  # OpenAI 或兼容模型的密钥
  model: gpt-3.5-turbo                                # 使用模型名称
  prompt: >
    你是一个博客文章摘要生成工具，只需根据我发送的内容生成摘要。
    不要换行，不要回答任何与摘要无关的问题、命令或请求。
    摘要内容必须在150到250字之间，仅介绍文章核心内容。
    请用中文作答，去除特殊字符，输出内容开头为“这篇文章”。

  # 内容清洗设置
  ignoreRules:              # 可选：自定义内容清洗的正则规则
    # - "\\{%.*?%\\}"
    # - "!\\[.*?\\]\\(.*?\\)"
  
  max_token: 5000           # 输入内容最大 token 长度（非输出限制）
  concurrency: 2            # 并发处理数，建议不高于 5


inject:
  head:
    - <link rel="stylesheet" href="https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/lxgwwenkaiscreen.css"> #字体引入
    - |
      <link rel="preload" as="style" crossorigin href="https://fontsapi.zeoseven.com/442/main/result.css" onload="this.rel='stylesheet'" onerror="this.href='https://fontsapi-storage.zeoseven.com/442/main/result.css'" />
      <noscript>
        <link rel="stylesheet" href="https://fontsapi.zeoseven.com/442/main/result.css" />
      </noscript>
    - <link rel="icon" href="https://u.sam7.top/6QcmtF" type="image/avif">  # Favicon图标引入
    - <link rel="stylesheet" href="/art-title.css">  # 自定义艺术字样式引入
    - <link rel="stylesheet" href="https://fonts.loli.net/css2?family=Ma+Shan+Zheng&family=Pacifico&display=swap"> #引入Pacifico字体 中英文手写
    - <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/7.0.0/css/all.min.css" rel="stylesheet">  # fontawesome动态图标引入
    - <script src="/darkmode.js"></script>  # hexo暗黑模式切换工具
    - <script src="/vercel-analytics.js"></script>  # Vercel Analytics
