name: Hexo部署（强制生成public目录）
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          lfs: true

      - name: 环境与目录全景检查
        run: |
          echo "===== 系统环境 ====="
          node -v
          npm -v
          hexo -v || echo "Hexo尚未安装"
          
          echo "===== 目录结构 ====="
          tree -L 3  # 显示3级目录，确认文件结构
          
          echo "===== 核心文件检查 ====="
          [ -d "themes/stellar" ] && echo "✅ 主题目录存在" || { echo "❌ 主题目录缺失"; exit 1; }
          [ -f "package.json" ] && echo "✅ package.json存在" || { echo "❌ package.json缺失"; exit 1; }
          [ -d "source" ] && echo "✅ source目录存在" || { echo "❌ source目录缺失（无内容可生成）"; exit 1; }
          [ "$(ls -A source)" ] && echo "✅ source目录有内容" || { echo "❌ source目录为空（无法生成页面）"; exit 1; }

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0  # 具体稳定版本，避免自动升级导致问题
          cache: 'npm'

      - name: 安装依赖（带完整日志）
        run: |
          echo "===== 安装Hexo CLI ====="
          npm install hexo-cli -g --verbose
          
          echo "===== 安装根目录依赖 ====="
          npm install --verbose  # 输出完整依赖安装日志
          
          echo "===== 安装主题依赖 ====="
          cd themes/stellar && npm install --verbose && cd ../../
          
          echo "===== 依赖版本确认 ====="
          npm list hexo  # 确认Hexo版本
          npm list hexo-theme-stellar  # 确认主题版本

      - name: 构建public目录（带调试日志）
        run: |
          echo "===== Hexo配置检查 ====="
          cat _config.yml  # 输出主配置
          cat themes/stellar/_config.yml  # 输出主题配置（关键！）
          
          echo "===== 清理旧构建 ====="
          hexo clean --debug
          
          echo "===== 开始生成public目录 ====="
          hexo generate --debug  # 调试模式输出所有生成细节
          
          echo "===== 构建后状态检查 ====="
          # 强制检查public目录
          if [ ! -d "public" ]; then
            echo "❌ 致命错误：public目录未生成！"
            echo "可能原因："
            echo "1. Hexo配置错误（如主题设置、路径错误）"
            echo "2. source目录无有效内容（如无.md文章）"
            echo "3. 依赖版本冲突（查看上方依赖安装日志）"
            exit 1
          fi
          
          # 检查public目录内容
          echo "===== public目录内容 ====="
          ls -la public
          file_count=$(find public -type f | wc -l)
          echo "public目录文件总数：$file_count"
          
          if [ $file_count -lt 5 ]; then
            echo "❌ 警告：public目录内容过少（少于5个文件），可能生成不完整"
            exit 1
          fi

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false

      - name: 部署后验证（关键！）
        run: |
          echo "===== 验证gh-pages分支内容 ====="
          git clone -b gh-pages https://github.com/${{ github.repository }} temp-gh-pages
          echo "gh-pages分支文件列表："
          ls -la temp-gh-pages
          if [ ! -f "temp-gh-pages/index.html" ]; then
            echo "❌ 部署失败：gh-pages分支无index.html"
            exit 1
          else
            echo "✅ 部署验证通过"
          fi

      # 其他平台部署保持不变
      - name: 部署到Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./public
          vercel-args: '--prod'
        continue-on-error: true

      - name: 部署到Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./public
          branch: main
        continue-on-error: true
